version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: interviewer-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: interviewer
      POSTGRES_PASSWORD: interviewer
      POSTGRES_DB: interviewer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
